# Generated by Django 5.2.8 on 2025-12-09 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_orderitem_cancellation_reason_orderitem_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('utm_source', models.CharField(help_text='Traffic source (e.g., google, facebook)', max_length=100)),
                ('utm_medium', models.CharField(help_text='Marketing medium (e.g., cpc, email)', max_length=100)),
                ('utm_campaign', models.CharField(help_text='Campaign name', max_length=100)),
                ('clicks', models.IntegerField(default=0, help_text='Total clicks/visits')),
                ('conversions', models.IntegerField(default=0, help_text='Total orders from this campaign')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue generated', max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UTMTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, help_text='Paid search keywords', max_length=100)),
                ('utm_content', models.CharField(blank=True, help_text='Ad variation', max_length=100)),
                ('referrer', models.URLField(blank=True, help_text='HTTP referrer')),
                ('landing_page', models.URLField(help_text='First page visited')),
                ('converted', models.BooleanField(default=False)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_entries', to='marketing.campaign')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utm_tracking', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utm_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UTM Tracking',
                'verbose_name_plural': 'UTM Tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='marketing_u_session_e87fcb_idx'), models.Index(fields=['utm_campaign', '-created_at'], name='marketing_u_utm_cam_247178_idx')],
            },
        ),
    ]
