# Generated by Django 5.2.8 on 2025-12-08 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_assign_category_commission_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Promotion name (e.g., 'Mirrors')", max_length=100)),
                ('discount_text', models.CharField(help_text="Discount display (e.g., 'UPTO 60% OFF')", max_length=100)),
                ('background_color', models.CharField(default='#334155', help_text='Hex color or CSS gradient', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/promotions/')),
                ('link_url', models.CharField(help_text='Link destination', max_length=500)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Promotion',
                'verbose_name_plural': 'Category Promotions',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier (e.g., 'frame', 'lamp')", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/categories/')),
                ('link_url', models.CharField(help_text='Link destination', max_length=500)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Featured Category',
                'verbose_name_plural': 'Featured Categories',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Main headline (e.g., 'HO HO HOME SALE')", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Secondary text', max_length=300)),
                ('background_color', models.CharField(default='#eab308', help_text='Hex color or CSS gradient', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostingEssential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Table Linens')", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/hosting/')),
                ('emoji', models.CharField(blank=True, help_text='Optional emoji representation', max_length=10)),
                ('link_url', models.CharField(help_text='Link destination', max_length=500)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hosting Essential',
                'verbose_name_plural': 'Hosting Essentials',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PremiumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Section title (e.g., 'Premium')", max_length=100)),
                ('subtitle', models.CharField(help_text="Section subtitle (e.g., 'museum quality')", max_length=200)),
                ('background_color', models.CharField(default='#f1f5f9', help_text='Hex color or CSS gradient', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/premium/')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=50)),
                ('link_url', models.CharField(help_text='Link destination', max_length=500)),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premium Section',
                'verbose_name_plural': 'Premium Sections',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Banner title (e.g., 'Lights & Lamps')", max_length=200)),
                ('discount_text', models.CharField(help_text="Discount display (e.g., 'UPTO 65% OFF')", max_length=100)),
                ('background_color', models.CharField(default='#065f46', help_text='Hex color or CSS gradient', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/banners/')),
                ('link_url', models.CharField(help_text='Where banner links to', max_length=500)),
                ('position', models.CharField(choices=[('large_left', 'Large Left'), ('large_right', 'Large Right'), ('side', 'Side Banner'), ('full_width', 'Full Width')], default='large_left', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(help_text='Deal start date')),
                ('end_date', models.DateField(help_text='Deal end date')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_deals', to='products.product')),
            ],
            options={
                'verbose_name': 'Deal of the Day',
                'verbose_name_plural': 'Deals of the Day',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
