# Generated by Django on 2025-12-11

from django.db import migrations
from datetime import date, timedelta


def populate_homepage_data(apps, schema_editor):
    """Populate all homepage sections with dummy data"""
    
    # Get models
    HeroBanner = apps.get_model('homepage', 'HeroBanner')
    PromotionalBanner = apps.get_model('homepage', 'PromotionalBanner')
    FeaturedCategory = apps.get_model('homepage', 'FeaturedCategory')
    HostingEssential = apps.get_model('homepage', 'HostingEssential')
    PremiumSection = apps.get_model('homepage', 'PremiumSection')
    CategoryPromotion = apps.get_model('homepage', 'CategoryPromotion')
    
    # 1. Create Hero Banners
    hero_banners = [
        {
            'title': 'DECOR YOUR SPACE',
            'subtitle': 'Elevate your home with our curated collection',
            'background_color': '#3b82f6',
            'is_active': True,
            'priority': 10
        },
        {
            'title': 'FESTIVE SPECIAL',
            'subtitle': 'Upto 70% OFF on selected items',
            'background_color': '#ef4444',
            'is_active': True,
            'priority': 9
        },
    ]
    
    for data in hero_banners:
        HeroBanner.objects.get_or_create(
            title=data['title'],
            defaults=data
        )
    
    # 2. Create Promotional Banners
    promo_banners = [
        {
            'title': 'Lights & Lamps',
            'discount_text': 'UPTO 65% OFF',
            'background_color': '#065f46',
            'link_url': '/products?category=lighting',
            'position': 'large_left',
            'priority': 10
        },
        {
            'title': 'Home Decor',
            'discount_text': 'UPTO 50% OFF',
            'background_color': '#7c2d12',
            'link_url': '/products?category=decor',
            'position': 'large_right',
            'priority': 9
        },
        {
            'title': 'Wall Art',
            'discount_text': 'NEW ARRIVALS',
            'background_color': '#581c87',
            'link_url': '/products?category=wall-art',
            'position': 'side',
            'priority': 8
        },
    ]
    
    for data in promo_banners:
        PromotionalBanner.objects.get_or_create(
            title=data['title'],
            defaults=data
        )
    
    # 3. Create Featured Categories
    featured_cats = [
        {
            'name': 'Picture Frames',
            'icon': 'frame',
            'link_url': '/products?category=frames',
            'priority': 1
        },
        {
            'name': 'Table Lamps',
            'icon': 'lamp',
            'link_url': '/products?category=lamps',
            'priority': 2
        },
        {
            'name': 'Wall Mirrors',
            'icon': 'mirror',
            'link_url': '/products?category=mirrors',
            'priority': 3
        },
        {
            'name': 'Cushions',
            'icon': 'cushion',
            'link_url': '/products?category=cushions',
            'priority': 4
        },
        {
            'name': 'Candles',
            'icon': 'candle',
            'link_url': '/products?category=candles',
            'priority': 5
        },
        {
            'name': 'Vases',
            'icon': 'vase',
            'link_url': '/products?category=vases',
            'priority': 6
        },
    ]
    
    for data in featured_cats:
        FeaturedCategory.objects.get_or_create(
            name=data['name'],
            defaults=data
        )
    
    # 4. Create Pooja Essentials (Hindu Worship Items)
    pooja_items = [
        {
            'name': 'Diyas & Lamps',
            'emoji': '🪔',
            'link_url': '/products?category=diyas',
            'priority': 1
        },
        {
            'name': 'Incense Holders',
            'emoji': '🕉️',
            'link_url': '/products?category=incense',
            'priority': 2
        },
        {
            'name': 'Pooja Thali',
            'emoji': '🛕',
            'link_url': '/products?category=pooja-thali',
            'priority': 3
        },
        {
            'name': 'Temple Bells',
            'emoji': '🔔',
            'link_url': '/products?category=bells',
            'priority': 4
        },
        {
            'name': 'Deity Idols',
            'emoji': '🙏',
            'link_url': '/products?category=idols',
            'priority': 5
        },
        {
            'name': 'Kalash & Containers',
            'emoji': '⚱️',
            'link_url': '/products?category=kalash',
            'priority': 6
        },
    ]
    
    for data in pooja_items:
        HostingEssential.objects.get_or_create(
            name=data['name'],
            defaults=data
        )
    
    # 5. Create Premium Sections
    premium_sections = [
        {
            'title': 'Premium',
            'subtitle': 'Museum Quality Art',
            'background_color': '#f1f5f9',
            'icon': 'sparkles',
            'link_url': '/products?filter=premium',
            'position': 'left',
            'priority': 10
        },
        {
            'title': 'Handcrafted',
            'subtitle': 'Artisan Collection',
            'background_color': '#fef3c7',
            'icon': 'palette',
            'link_url': '/products?filter=handcrafted',
            'position': 'right',
            'priority': 9
        },
    ]
    
    for data in premium_sections:
        PremiumSection.objects.get_or_create(
            title=data['title'],
            subtitle=data['subtitle'],
            defaults=data
        )
    
    # 6. Create Category Promotions
    cat_promos = [
        {
            'name': 'Mirrors',
            'discount_text': 'UPTO 60% OFF',
            'background_color': '#1e40af',
            'link_url': '/products?category=mirrors',
            'priority': 1
        },
        {
            'name': 'Wall Decor',
            'discount_text': 'UPTO 55% OFF',
            'background_color': '#7e22ce',
            'link_url': '/products?category=wall-decor',
            'priority': 2
        },
        {
            'name': 'Rugs & Carpets',
            'discount_text': 'UPTO 50% OFF',
            'background_color': '#be123c',
            'link_url': '/products?category=rugs',
            'priority': 3
        },
        {
            'name': 'Lighting',
            'discount_text': 'UPTO 65% OFF',
            'background_color': '#0f766e',
            'link_url': '/products?category=lighting',
            'priority': 4
        },
    ]
    
    for data in cat_promos:
        CategoryPromotion.objects.get_or_create(
            name=data['name'],
            defaults=data
        )


def reverse_populate(apps, schema_editor):
    """Remove dummy data if migration is reversed"""
    HeroBanner = apps.get_model('homepage', 'HeroBanner')
    PromotionalBanner = apps.get_model('homepage', 'PromotionalBanner')
    FeaturedCategory = apps.get_model('homepage', 'FeaturedCategory')
    HostingEssential = apps.get_model('homepage', 'HostingEssential')
    PremiumSection = apps.get_model('homepage', 'PremiumSection')
    CategoryPromotion = apps.get_model('homepage', 'CategoryPromotion')
    
    # Delete all created items
    HeroBanner.objects.filter(title__in=['DECOR YOUR SPACE', 'FESTIVE SPECIAL']).delete()
    PromotionalBanner.objects.filter(title__in=['Lights & Lamps', 'Home Decor', 'Wall Art']).delete()
    FeaturedCategory.objects.filter(name__in=['Picture Frames', 'Table Lamps', 'Wall Mirrors', 'Cushions', 'Candles', 'Vases']).delete()
    HostingEssential.objects.filter(name__in=['Diyas & Lamps', 'Incense Holders', 'Pooja Thali', 'Temple Bells', 'Deity Idols', 'Kalash & Containers']).delete()
    PremiumSection.objects.filter(title__in=['Premium', 'Handcrafted']).delete()
    CategoryPromotion.objects.filter(name__in=['Mirrors', 'Wall Decor', 'Rugs & Carpets', 'Lighting']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_homepage_data, reverse_populate),
    ]
