# Generated by Django 5.2.8 on 2025-12-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_populate_homepage_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostingessential',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Pooja Essential', 'verbose_name_plural': 'Pooja Essentials'},
        ),
        migrations.AlterField(
            model_name='hostingessential',
            name='name',
            field=models.CharField(help_text="Category name (e.g., 'Diyas', 'Incense Holders')", max_length=100),
        ),
    ]
