"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# Check if we are running collectstatic (build phase)
import sys
if 'collectstatic' in sys.argv:
    SECRET_KEY = SECRET_KEY or 'django-insecure-build-key-for-static-collection'

# Fallback strictly for dev
if not SECRET_KEY and os.getenv('DEBUG') == 'True':
    SECRET_KEY = 'django-insecure-fallback-dev-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Security Headers (Production)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,.uparwala.in,.railway.app').split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://uparwala.in',
    'https://www.uparwala.in',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',  # Required for dj-rest-auth
    'rest_framework_simplejwt',
    'corsheaders',
    
    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # REST Auth
    'dj_rest_auth',
    'dj_rest_auth.registration',

    # Local
    'users',
    'products',
    'orders',
    'vendors',
    'payments',
    'marketing',  # Phase 8
    'analytics',  # Phase 7
    'notifications',
    'homepage',
    'promotions',  # New app for coupons and promotions
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR}/db.sqlite3',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Storage Configuration
# Defined using STORAGES for Django 4.2+ compatibility
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}

# Media files configuration
USE_R2_STORAGE = os.getenv('USE_R2_STORAGE', 'False') ==  'True'

print(f"DEBUG SETTINGS: USE_R2_STORAGE env var = {os.getenv('USE_R2_STORAGE')}")
print(f"DEBUG SETTINGS: USE_R2_STORAGE boolean = {USE_R2_STORAGE}")

if USE_R2_STORAGE:
    print("DEBUG SETTINGS: R2 Storage is ENABLED")
    # Cloudflare R2 Storage Configuration
    INSTALLED_APPS += ['storages']
    
    # R2 Configuration
    AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME', 'uparwala-media')
    AWS_S3_ENDPOINT_URL = f"https://{os.getenv('R2_ACCOUNT_ID')}.r2.cloudflarestorage.com"
    AWS_S3_REGION_NAME = 'auto'  # R2 uses 'auto' for region
    
    print(f"DEBUG SETTINGS: AWS_STORAGE_BUCKET_NAME = {AWS_STORAGE_BUCKET_NAME}")
    print(f"DEBUG SETTINGS: AWS_S3_ENDPOINT_URL = {AWS_S3_ENDPOINT_URL}")
    
    # Storage settings
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # 1 day cache
    }
    AWS_QUERYSTRING_AUTH = False  # Don't add auth params to URLs
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    # Configure custom domain for public access
    # This ensures obj.image.url returns the public URL instead of the S3 endpoint
    r2_public_url = os.getenv('R2_PUBLIC_URL', 'https://pub-d1ba09fdc860448fad2976607846ddb1.r2.dev/')
    AWS_S3_CUSTOM_DOMAIN = r2_public_url.replace('https://', '').replace('http://', '').rstrip('/')
    
    print(f"DEBUG SETTINGS: AWS_S3_CUSTOM_DOMAIN = {AWS_S3_CUSTOM_DOMAIN}")
    
    # Use custom R2 storage backend with timeout config (Django 4.2+)
    STORAGES["default"] = {
        "BACKEND": "config.storage_backends.CloudflareR2Storage",
    }
    
    print(f"DEBUG SETTINGS: STORAGES['default'] = {STORAGES['default']}")
    
    # Public URL for media files
    MEDIA_URL = os.getenv('R2_PUBLIC_URL', 'https://pub-d1ba09fdc860448fad2976607846ddb1.r2.dev/')
    if not MEDIA_URL.endswith('/'):
        MEDIA_URL += '/'
    
    print(f"DEBUG SETTINGS: MEDIA_URL = {MEDIA_URL}")
else:
    print("DEBUG SETTINGS: R2 Storage is DISABLED - using local filesystem")
    # Local development - use local filesystem
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site ID for django.contrib.sites
SITE_ID = 1

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'users.backends.AllowInactiveUserBackend',  # Custom backend to allow inactive users
    'allauth.account.auth_backends.AuthenticationBackend',  # User Auth
]

# Allauth Settings (Modern Format - No Deprecation Warnings)
# Allauth Settings (Modern Format)
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
LOGIN_URL = 'http://localhost:5173/login'

# New Allauth Configuration (Replaces deprecated settings)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username', 'password1', 'password2']
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto-create account on social login
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Skip email verification for social accounts

# Google OAuth Settings (will be configured in admin)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
        }
    }
}

# REST Auth Settings
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'access_token',
    'JWT_AUTH_REFRESH_COOKIE': 'refresh_token',
    'JWT_AUTH_HTTPONLY': True,
    'JWT_AUTH_SAMESITE': 'Lax',  # 'None' if cross-site but requires Secure=True
    'JWT_AUTH_SECURE': not DEBUG, # True in production
}

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# CORS Settings
# CORS Settings
def clean_cors_origin(url):
    """Remove path and trailing slash from URL for CORS settings"""
    if not url:
        return ""
    from urllib.parse import urlparse
    parsed = urlparse(url)
    if parsed.scheme and parsed.netloc:
        return f"{parsed.scheme}://{parsed.netloc}"
    return url.strip("/").split("?")[0].split("#")[0]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    clean_cors_origin(os.getenv('FRONTEND_URL', 'http://localhost:5173')),
    "https://uparwala.in",
    "https://www.uparwala.in",
]

# Allow adding more origins via comma-separated env var
if os.getenv('CORS_ALLOWED_ORIGINS'):
    for origin in os.getenv('CORS_ALLOWED_ORIGINS').split(','):
        cleaned = clean_cors_origin(origin.strip())
        if cleaned:
            CORS_ALLOWED_ORIGINS.append(cleaned)

CORS_ALLOW_CREDENTIALS = True

# DRF Settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication', # Enable Cookie Auth
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/day',
        'user': '5000/day'
    }
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}

# Override JWT user authentication to allow inactive users
def custom_user_authentication_rule(user):
    """Allow all users including inactive ones to get JWT tokens"""
    return True

SIMPLE_JWT['USER_AUTHENTICATION_RULE'] = 'config.settings.custom_user_authentication_rule'

# Razorpay Configuration
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', '')

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Frontend URL for email links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Celery Configuration
# Railway provides REDIS_URL, so we check that first
CELERY_BROKER_URL = os.getenv('REDIS_URL', os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0'))
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0'))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Shiprocket Settings
SHIPROCKET_WEBHOOK_SECRET = os.getenv('SHIPROCKET_WEBHOOK_SECRET', '')
SHIPROCKET_AUTO_CREATE = os.getenv('SHIPROCKET_AUTO_CREATE', 'True') == 'True'
SHIPROCKET_AUTO_AWB = os.getenv('SHIPROCKET_AUTO_AWB', 'False') == 'True'
SHIPROCKET_EMAIL = os.getenv('SHIPROCKET_EMAIL')
SHIPROCKET_PASSWORD = os.getenv('SHIPROCKET_PASSWORD')
