# Generated by Django 5.2.8 on 2025-12-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderreturn_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paid_to_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
