# Generated by Django 5.2.8 on 2025-12-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_commission_amount_orderitem_paid_to_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiprocketConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('api_token', models.CharField(blank=True, max_length=500)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pickup_location', models.CharField(help_text='Name of pickup location', max_length=255)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_state', models.CharField(max_length=100)),
                ('pickup_pincode', models.CharField(max_length=10)),
                ('pickup_phone', models.CharField(max_length=15)),
                ('pickup_name', models.CharField(default='Warehouse', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shiprocket Configuration',
                'verbose_name_plural': 'Shiprocket Configurations',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='awb_code',
            field=models.CharField(blank=True, help_text='Air Waybill Code', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiprocket_order_id', models.CharField(max_length=100, unique=True)),
                ('shiprocket_shipment_id', models.CharField(blank=True, max_length=100)),
                ('awb_code', models.CharField(blank=True, max_length=100)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('courier_id', models.IntegerField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('label_url', models.URLField(blank=True)),
                ('manifest_url', models.URLField(blank=True)),
                ('invoice_url', models.URLField(blank=True)),
                ('pickup_scheduled', models.BooleanField(default=False)),
                ('pickup_token_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Shipment Tracking',
                'verbose_name_plural': 'Shipment Trackings',
            },
        ),
        migrations.CreateModel(
            name='OrderTrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('status_code', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('shiprocket_status', models.CharField(blank=True, max_length=100)),
                ('courier_status', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='orders.order')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.shipmenttracking')),
            ],
            options={
                'verbose_name': 'Order Tracking Status',
                'verbose_name_plural': 'Order Tracking Statuses',
                'ordering': ['-timestamp'],
            },
        ),
    ]
