# Generated by Django 5.2.8 on 2025-12-09 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_cancellation_reason_orderitem_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CODPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'COD Pincode',
                'verbose_name_plural': 'COD Pincodes',
            },
        ),
        migrations.CreateModel(
            name='GiftOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='gift_wrapping/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gift Option',
                'verbose_name_plural': 'Gift Options',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AddressVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed'), ('manual_review', 'Manual Review Required')], default='pending', max_length=20)),
                ('verified_address', models.TextField(blank=True)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_verification', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address Verification',
                'verbose_name_plural': 'Address Verifications',
            },
        ),
        migrations.CreateModel(
            name='OrderGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_message', models.TextField(blank=True, max_length=500)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.giftoption')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_details', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Gift',
                'verbose_name_plural': 'Order Gifts',
            },
        ),
    ]
