# Generated by Django 5.2.8 on 2025-12-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_serviceablepincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_note',
            field=models.TextField(blank=True, help_text='Notes from customer at checkout'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
