# Generated by Django 5.2.8 on 2025-12-11 13:30

from django.db import migrations


def populate_cod_pincodes(apps, schema_editor):
    """Populate COD serviceable pincodes for major Indian cities"""
    CODPincode = apps.get_model('orders', 'CODPincode')
    
    # Major city pincodes that should support COD
    pincodes_data = [
        # Delhi
        {'pincode': '110001', 'city': 'New Delhi', 'state': 'Delhi', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '110002', 'city': 'New Delhi', 'state': 'Delhi', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '110005', 'city': 'New Delhi', 'state': 'Delhi', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '110016', 'city': 'New Delhi', 'state': 'Delhi', 'is_active': True, 'max_order_value': 50000.00},
        
        # Mumbai
        {'pincode': '400001', 'city': 'Mumbai', 'state': 'Maharashtra', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '400050', 'city': 'Mumbai', 'state': 'Maharashtra', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '400051', 'city': 'Mumbai', 'state': 'Maharashtra', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '400070', 'city': 'Mumbai', 'state': 'Maharashtra', 'is_active': True, 'max_order_value': 50000.00},
        
        # Bangalore
        {'pincode': '560001', 'city': 'Bangalore', 'state': 'Karnataka', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '560002', 'city': 'Bangalore', 'state': 'Karnataka', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '560025', 'city': 'Bangalore', 'state': 'Karnataka', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '560100', 'city': 'Bangalore', 'state': 'Karnataka', 'is_active': True, 'max_order_value': 50000.00},
        
        # Ahmedabad
        {'pincode': '380001', 'city': 'Ahmedabad', 'state': 'Gujarat', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '380009', 'city': 'Ahmedabad', 'state': 'Gujarat', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '380015', 'city': 'Ahmedabad', 'state': 'Gujarat', 'is_active': True, 'max_order_value': 50000.00},
        
        # Pune
        {'pincode': '411001', 'city': 'Pune', 'state': 'Maharashtra', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '411005', 'city': 'Pune', 'state': 'Maharashtra', 'is_active': True, 'max_order_value': 50000.00},
        
        # Hyderabad
        {'pincode': '500001', 'city': 'Hyderabad', 'state': 'Telangana', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '500016', 'city': 'Hyderabad', 'state': 'Telangana', 'is_active': True, 'max_order_value': 50000.00},
        
        # Chennai
        {'pincode': '600001', 'city': 'Chennai', 'state': 'Tamil Nadu', 'is_active': True, 'max_order_value': 50000.00},
        {'pincode': '600020', 'city': 'Chennai', 'state': 'Tamil Nadu', 'is_active': True, 'max_order_value': 50000.00},
    ]
    
    # Create or update pincodes
    for data in pincodes_data:
        CODPincode.objects.update_or_create(
            pincode=data['pincode'],
            defaults={
                'city': data['city'],
                'state': data['state'],
                'is_active': data['is_active'],
                'max_order_value': data['max_order_value']
            }
        )


def reverse_populate(apps, schema_editor):
    """Remove populated pincodes if migration is reversed"""
    CODPincode = apps.get_model('orders', 'CODPincode')
    pincodes_to_remove = [
        '110001', '110002', '110005', '110016',  # Delhi
        '400001', '400050', '400051', '400070',  # Mumbai
        '560001', '560002', '560025', '560100',  # Bangalore
        '380001', '380009', '380015',  # Ahmedabad
        '411001', '411005',  # Pune
        '500001', '500016',  # Hyderabad
        '600001', '600020',  # Chennai
    ]
    CODPincode.objects.filter(pincode__in=pincodes_to_remove).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_ordernote'),
    ]

    operations = [
        migrations.RunPython(populate_cod_pincodes, reverse_populate),
    ]
