# Generated by Django 5.2.8 on 2025-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_populate_cod_pincodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CGST amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IGST amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SGST amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total tax for this item', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate applied (%)', max_digits=5),
        ),
    ]
