# Generated by Django 5.2.8 on 2025-12-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_cart_session_id_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiprocketPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=10, unique=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('zone', models.CharField(blank=True, help_text='East, West, North, South', max_length=10)),
                ('is_serviceable', models.BooleanField(db_index=True, default=True)),
                ('is_cod_available', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviceable Pincode Master',
                'verbose_name_plural': 'Serviceable Pincode Masters',
                'indexes': [models.Index(fields=['state', 'city'], name='orders_ship_state_b2adb2_idx')],
            },
        ),
    ]
