# Generated by Django 5.2.8 on 2025-12-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_shiprocketpincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiprocketpincode',
            name='division_name',
            field=models.CharField(blank=True, db_index=True, help_text='Division Name from CSV', max_length=100),
        ),
    ]
