# Generated by Django 5.2.8 on 2025-12-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_guest_checkout_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_request_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='review_request_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
