# Generated by Django 5.2.8 on 2026-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_shipmenttracking_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceablepincode',
            name='area',
            field=models.CharField(blank=True, db_index=True, help_text='Area/Locality', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceablepincode',
            name='pincode',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='serviceablepincode',
            unique_together={('pincode', 'area')},
        ),
        migrations.AddIndex(
            model_name='serviceablepincode',
            index=models.Index(fields=['pincode', 'area'], name='orders_serv_pincode_30a6ac_idx'),
        ),
    ]
