release: python3 manage.py migrate --noinput && python3 manage.py seed_footer
web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 120 --access-logfile - --error-logfile - --log-level info
