# Generated by Django 5.2.8 on 2025-11-29 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlist'),
        ('vendors', '0002_alter_withdrawal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='bulk_imports/')),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_history', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name_plural': 'Bulk import histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
