# Generated by Django 5.2.8 on 2025-12-04 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cmspage_coupon_productmoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission rate for products in this category (2-10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
