# Generated by Django

from django.db import migrations
from decimal import Decimal
import random


def assign_random_commission_rates(apps, schema_editor):
    """Assign random commission rates between 2% and 10% to all existing categories"""
    Category = apps.get_model('products', 'Category')
    
    for category in Category.objects.all():
        # Generate random commission rate between 2.00 and 10.00
        random_rate = Decimal(str(round(random.uniform(2.0, 10.0), 2)))
        category.commission_rate = random_rate
        category.save()
        print(f"Assigned {random_rate}% commission to category: {category.name}")


def reverse_commission_rates(apps, schema_editor):
    """Reset commission rates to default"""
    Category = apps.get_model('products', 'Category')
    Category.objects.all().update(commission_rate=Decimal('5.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_commission_rate'),
    ]

    operations = [
        migrations.RunPython(assign_random_commission_rates, reverse_commission_rates),
    ]
