# Generated by Django 5.2.8 on 2025-12-09 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_recentlyviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='For perishable items', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='handling_time',
            field=models.IntegerField(default=2, help_text='Days required to prepare for shipping'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_country',
            field=models.CharField(blank=True, help_text='Country of manufacture', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_instructions',
            field=models.TextField(blank=True, help_text='Safety warnings and instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='whats_in_box',
            field=models.TextField(blank=True, help_text='List items included in the package'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand'),
        ),
    ]
