# Generated by Django 5.2.8 on 2025-12-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productbundle_productcomparison_productvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('default_sort_order', models.CharField(choices=[('menu_order', 'Custom Ordering'), ('name', 'Name'), ('name_num', 'Name (Numeric)'), ('id', 'Term ID')], default='menu_order', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='display_type',
            field=models.CharField(choices=[('default', 'Default'), ('products', 'Products'), ('subcategories', 'Subcategories'), ('both', 'Both')], default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='AttributeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='products.globalattribute')),
            ],
            options={
                'ordering': ['menu_order', 'name'],
                'unique_together': {('attribute', 'slug')},
            },
        ),
    ]
