# Generated by Django 5.2.8 on 2025-12-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_globalattribute_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicability_type',
            field=models.CharField(choices=[('site_wide', 'Site Wide'), ('specific_products', 'Specific Products'), ('specific_categories', 'Specific Categories'), ('new_user', 'New Users Only')], default='site_wide', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='specific_categories',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='specific_products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.product'),
        ),
    ]
