# Generated by Django 5.2.8 on 2025-12-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_coupon_applicability_type_coupon_specific_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., GST 18%', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Total tax rate %', max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, help_text='Central GST %', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, help_text='State GST %', max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, help_text='Integrated GST %', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sold_individually',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_class',
            field=models.CharField(blank=True, help_text='Deprecated: Use tax_slab instead', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_slab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.taxslab'),
        ),
    ]
