# Generated by Django 5.2.8 on 2025-12-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_taxslab_product_sold_individually_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Customer email for notification', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Customer phone for SMS notification', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False, help_text='Whether customer has been notified')),
                ('notified_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Notification Request',
                'verbose_name_plural': 'Stock Notification Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
