# Generated by Django 5.2.8 on 2025-12-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_stocknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Display this category in the navigation menu'),
        ),
    ]
