# Generated by Django 5.2.8 on 2025-12-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='Order in which this category appears in the menu (lower numbers first)'),
        ),
    ]
