# Generated by Django 5.2.8 on 2025-12-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_category_menu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_exchangeable',
            field=models.BooleanField(default=False, help_text='Product can be exchanged'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='Product can be returned'),
        ),
    ]
