# Generated by Django 5.2.8 on 2026-01-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panditprofile',
            name='service_radius_km',
            field=models.PositiveIntegerField(default=10, help_text='Maximum distance (in km) this Pandit is willing to travel'),
        ),
    ]
