# Generated by Django 5.2.8 on 2025-12-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_commissionsettings_payoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='serviceable_pincodes',
            field=models.TextField(blank=True, help_text='Comma-separated list of pincodes. Leave empty to serve all (subject to global restrictions).'),
        ),
    ]
