# Generated by Django 5.2.8 on 2025-12-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorprofile_serviceable_pincodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='shiprocket_pickup_location_name',
            field=models.CharField(blank=True, help_text='Unique Pickup Location Name in Shiprocket', max_length=100),
        ),
    ]
