# Generated by Django 5.2.8 on 2025-12-10 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorprofile_shiprocket_pickup_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the vendor was approved', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected'),
        ),
    ]
