# Generated by Django 5.2.8 on 2025-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendorprofile_approved_at_vendorprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='cancelled_cheque',
            field=models.FileField(blank=True, help_text='Upload cancelled cheque or passbook copy', null=True, upload_to='vendor_docs/bank/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='food_license_certificate',
            field=models.FileField(blank=True, help_text='Upload FSSAI license', null=True, upload_to='vendor_docs/food_license/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='food_license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_food_vendor',
            field=models.BooleanField(default=False, help_text='Is this vendor selling food products?'),
        ),
    ]
