# Generated by Django manually
from django.db import migrations

def populate_vendor_addresses(apps, schema_editor):
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    for vendor in VendorProfile.objects.all():
        updated = False
        if not vendor.address:
            vendor.address = "123 Market Street, Andheri West"
            updated = True
        if not vendor.city:
            vendor.city = "Mumbai"
            updated = True
        if not vendor.state:
            vendor.state = "Maharashtra"
            updated = True
        if not vendor.zip_code:
            vendor.zip_code = "400053"
            updated = True
        if not vendor.country:
            vendor.country = "India"
            updated = True
        if not vendor.phone:
            vendor.phone = "9876543210"
            updated = True
            
        if updated:
            vendor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendorprofile_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_vendor_addresses),
    ]
