# Generated by Django 5.2.8 on 2026-01-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_populate_vendor_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='commission_type',
        ),
        migrations.DeleteModel(
            name='CommissionSettings',
        ),
    ]
