# Generated by Django 5.2.8 on 2026-01-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_remove_vendorprofile_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='aadhar_card',
            field=models.FileField(blank=True, help_text='Aadhar Card (Address Proof)', null=True, upload_to='vendor_docs/aadhar/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_proof',
            field=models.FileField(blank=True, help_text='Shop & Establishment / Udham / Trade License', null=True, upload_to='vendor_docs/business/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_proof_remarks',
            field=models.TextField(blank=True, help_text='Remarks if business proof not available'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='gst_certificate',
            field=models.FileField(blank=True, help_text='GST Certificate (Optional)', null=True, upload_to='vendor_docs/gst/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='non_gst_declaration_accepted',
            field=models.BooleanField(default=False, help_text='Vendor accepted Non-GST declaration'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='non_gst_declaration_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='non_gst_declaration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_card',
            field=models.FileField(blank=True, help_text='PAN Card (Firm or Individual)', null=True, upload_to='vendor_docs/pan/'),
        ),
    ]
