# Generated by Django 5.2.8 on 2026-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendorprofile_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='delhivery_warehouse_name',
            field=models.CharField(blank=True, help_text='Registered Warehouse Name in Delhivery', max_length=100),
        ),
    ]
