# Generated by Django 5.2.8 on 2026-01-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_shippingzone_taxrate_delete_paymentwebhook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount for free shipping. Leave empty to always charge shipping.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Shipping Settings',
                'verbose_name_plural': 'Shipping Settings',
            },
        ),
    ]
