# Generated by Django 5.2.8 on 2025-12-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_recentlyviewed'),
        ('users', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, help_text="User's favorite product categories", related_name='preferred_by_users', to='products.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('bn', 'Bengali')], default='en', max_length=10),
        ),
    ]
