# Generated by Django 5.2.8 on 2025-12-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_careerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Manager role - can only add/approve vendors'),
        ),
    ]
