# Generated by Django 5.2.8 on 2026-01-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_is_manager_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=False, help_text='Pandit/Service Provider role'),
        ),
    ]
